spring:
  jpa:
    show-sql: true
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true    
    enabled: true
    mixed: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydb
    username: musala
    password: musala
springdoc:
  swagger-ui:
    path=/swagger-ui.html
checkBatteryLevel: '0 */5 * * * *'